manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 8bdd270c91a6aeb9686c2d32096040558b967a9e
      import: app/west.yml
  self:
    path: config
